// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(NoratorContext))]
    [Migration("20230603130323_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1963, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Johnny Depp"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1962, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Steve Carell"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2004, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Millie Bobby Brown"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1980, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Justin Roiland"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2000, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Auli'i Cravalho"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1944, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Craig T. Nelson"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1929, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Edward Asner"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1972, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Hale"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1980, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie Hunnam"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1983, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Henry Cavill"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1916, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gregory Peck"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1977, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom Hardy"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1989, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniel Radcliffe"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1954, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Travolta"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1958, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tim Robbins"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1969, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Matthew McConaughey"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1924, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marlon Brando"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1981, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bryce Dallas Howard"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1956, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bryan Cranston"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1986, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kit Harington"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1986, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emilia Clarke"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1952, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Liam Neeson"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1985, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gal Gadot"
                        });
                });

            modelBuilder.Entity("Core.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumberOfSubscribers")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentCategoryId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentCategoryId = 1,
                            Name = "Don`t Look Up",
                            NumberOfSubscribers = 1,
                            ReleaseDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ContentCategoryId = 1,
                            Name = "Charlie and the Chocolate Factory",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ContentCategoryId = 2,
                            Name = "The Office",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ContentCategoryId = 2,
                            Name = "Stranger Things",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ContentCategoryId = 2,
                            Name = "Rick and Morty",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2013, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ContentCategoryId = 3,
                            Name = "Moana",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2016, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ContentCategoryId = 3,
                            Name = "The Incredibles",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2004, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ContentCategoryId = 3,
                            Name = "Up",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2009, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ContentCategoryId = 4,
                            Name = "Mass Effect Legendary Edition",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            ContentCategoryId = 4,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            ContentCategoryId = 4,
                            Name = "The Witcher 3: Wild Hunt",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            ContentCategoryId = 5,
                            Name = "To Kill a Mockingbird",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            ContentCategoryId = 5,
                            Name = "1984",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            ContentCategoryId = 5,
                            Name = "Harry Potter and the Philosopher's Stone",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            ContentCategoryId = 1,
                            Name = "Pulp Fiction",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            ContentCategoryId = 1,
                            Name = "The Shawshank Redemption",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            ContentCategoryId = 1,
                            Name = "Interstellar",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2014, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            ContentCategoryId = 1,
                            Name = "Avengers: Endgame",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            ContentCategoryId = 1,
                            Name = "The Godfather",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            ContentCategoryId = 2,
                            Name = "Black Mirror",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2011, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            ContentCategoryId = 2,
                            Name = "Breaking Bad",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            ContentCategoryId = 2,
                            Name = "Game of Thrones",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            ContentCategoryId = 3,
                            Name = "Finding Nemo",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2003, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            ContentCategoryId = 3,
                            Name = "Toy Story",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1995, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            ContentCategoryId = 3,
                            Name = "Frozen",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2013, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            ContentCategoryId = 4,
                            Name = "Red Dead Redemption 2",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            ContentCategoryId = 4,
                            Name = "The Elder Scrolls V: Skyrim",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            ContentCategoryId = 4,
                            Name = "Minecraft",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            ContentCategoryId = 5,
                            Name = "The Great Gatsby",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            ContentCategoryId = 1,
                            Name = "The Hangover",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2009, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            ContentCategoryId = 1,
                            Name = "La La Land",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            ContentCategoryId = 1,
                            Name = "Inception",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            ContentCategoryId = 1,
                            Name = "The Notebook",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2004, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            ContentCategoryId = 2,
                            Name = "The Big Bang Theory",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2007, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            ContentCategoryId = 2,
                            Name = "Friends",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode IV - A New Hope",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode V - The Empire Strikes Back",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode VI - Return of the Jedi",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode I - The Phantom Menace",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode II - Attack of the Clones",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode III - Revenge of the Sith",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode VII - The Force Awakens",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode VIII - The Last Jedi",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2017, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            ContentCategoryId = 1,
                            Name = "Star Wars: Episode IX - The Rise of Skywalker",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            ContentCategoryId = 2,
                            Name = "Star Wars: The Clone Wars",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2008, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            ContentCategoryId = 2,
                            Name = "Star Wars Rebels",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2014, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            ContentCategoryId = 2,
                            Name = "The Mandalorian",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            ContentCategoryId = 2,
                            Name = "Star Wars: The Bad Batch",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            ContentCategoryId = 4,
                            Name = "Among Us",
                            NumberOfSubscribers = 0,
                            ReleaseDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Core.Entities.Content_Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("ContentActors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ContentId = 1
                        },
                        new
                        {
                            ActorId = 2,
                            ContentId = 2
                        },
                        new
                        {
                            ActorId = 3,
                            ContentId = 3
                        },
                        new
                        {
                            ActorId = 4,
                            ContentId = 4
                        },
                        new
                        {
                            ActorId = 5,
                            ContentId = 5
                        },
                        new
                        {
                            ActorId = 6,
                            ContentId = 6
                        },
                        new
                        {
                            ActorId = 7,
                            ContentId = 7
                        },
                        new
                        {
                            ActorId = 8,
                            ContentId = 8
                        },
                        new
                        {
                            ActorId = 9,
                            ContentId = 9
                        },
                        new
                        {
                            ActorId = 12,
                            ContentId = 12
                        },
                        new
                        {
                            ActorId = 13,
                            ContentId = 33
                        },
                        new
                        {
                            ActorId = 14,
                            ContentId = 14
                        },
                        new
                        {
                            ActorId = 15,
                            ContentId = 15
                        },
                        new
                        {
                            ActorId = 16,
                            ContentId = 16
                        },
                        new
                        {
                            ActorId = 17,
                            ContentId = 17
                        },
                        new
                        {
                            ActorId = 18,
                            ContentId = 18
                        },
                        new
                        {
                            ActorId = 19,
                            ContentId = 19
                        },
                        new
                        {
                            ActorId = 21,
                            ContentId = 21
                        },
                        new
                        {
                            ActorId = 22,
                            ContentId = 22
                        },
                        new
                        {
                            ActorId = 23,
                            ContentId = 22
                        },
                        new
                        {
                            ActorId = 24,
                            ContentId = 40
                        });
                });

            modelBuilder.Entity("Core.Entities.Content_Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("ContentGenres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            ContentId = 1
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 1
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 1
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 2
                        },
                        new
                        {
                            GenreId = 5,
                            ContentId = 2
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 2
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 3
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 4
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 4
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 5
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 5
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 6
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 7
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 8
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 9
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 10
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 11
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 12
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 13
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 14
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 15
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 16
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 17
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 18
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 19
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 20
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 21
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 22
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 23
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 24
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 25
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 26
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 27
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 28
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 30
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 31
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 32
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 33
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 34
                        },
                        new
                        {
                            GenreId = 2,
                            ContentId = 35
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 36
                        },
                        new
                        {
                            GenreId = 4,
                            ContentId = 37
                        },
                        new
                        {
                            GenreId = 3,
                            ContentId = 38
                        },
                        new
                        {
                            GenreId = 1,
                            ContentId = 39
                        },
                        new
                        {
                            GenreId = 5,
                            ContentId = 39
                        },
                        new
                        {
                            GenreId = 5,
                            ContentId = 40
                        });
                });

            modelBuilder.Entity("Core.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("ContentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Series"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Book"
                        });
                });

            modelBuilder.Entity("Core.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Admin",
                            Password = "123Admin#",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Tarakan",
                            Password = "123Tarakan#",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.User_Content", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("UserContents");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            ContentId = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.Content", b =>
                {
                    b.HasOne("Core.Entities.ContentCategory", "ContentCategory")
                        .WithMany("Contents")
                        .HasForeignKey("ContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentCategory");
                });

            modelBuilder.Entity("Core.Entities.Content_Actor", b =>
                {
                    b.HasOne("Core.Entities.Actor", "Actor")
                        .WithMany("Content_Actors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Content", "Content")
                        .WithMany("Content_Actors")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Core.Entities.Content_Genre", b =>
                {
                    b.HasOne("Core.Entities.Content", "Content")
                        .WithMany("Content_Genres")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Genre", "Genre")
                        .WithMany("Content_Genres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Core.Entities.User_Content", b =>
                {
                    b.HasOne("Core.Entities.Content", "Content")
                        .WithMany("User_Contents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("User_Contents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Actor", b =>
                {
                    b.Navigation("Content_Actors");
                });

            modelBuilder.Entity("Core.Entities.Content", b =>
                {
                    b.Navigation("Content_Actors");

                    b.Navigation("Content_Genres");

                    b.Navigation("User_Contents");
                });

            modelBuilder.Entity("Core.Entities.ContentCategory", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Core.Entities.Genre", b =>
                {
                    b.Navigation("Content_Genres");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("User_Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
